### ISSUE TITLE
Files missing from the project

### ISSUE THREAD

**Issue by abhishekbaghel05** [leonlulu/DeepLayout#2]
I am not able to find PageAnalyse.py and example.py. Is the code is removed?

**Comment by leonlulu** [comment]
It's a project worked with commercial company. Sorry we cannot make the code open source.

**Comment by leonlulu** [comment]
Sorry we can not make the source code public.

**Comment by DevLob-zz** [comment]
so one question please as source not available
first step we prepare our data-set with original image and labels 
second step learn this [original + label] and generate a model 
third step is test against a testing pages 
the model should predict bounding box for each region as it learned 
is this correct another question please is all pages should be same dimension learning and testing  

best regards and thanks for your share and time
