### ISSUE TITLE
Code selling

### ISSUE THREAD

**Issue by DELTA37** [leonlulu/DeepLayout#5]
If your code is not open, can I buy your code with pretrained model?
My contacts: gkasparyants@gmail.com, +79263455382, Russian number

**Comment by mistersherlock** [comment]
Can I buy your code too)? Contact me by mr_sherlock@yahoo.com

**Comment by lvaleriu** [comment]
Same here .... skype contact: l_valeriu
Thanks!

**Comment by kennethcwq** [comment]
Any updates? Thanks!

**Comment by leonlulu** [comment]
It's a project worked with commercial company. Sorry the code is not for selling. Thanks for your understanding.

**Comment by leonlulu** [comment]
Sorry the code is not for selling.
